config/routes.rb
SalesSafari::Application.routes.draw do
  root "trackers#new"
  resources :trackers, path: :t, only: [:new, :create, :show] do
    resources :subjects, path: :s, only: [:create] do
      post :vote, on: :member
    end
  end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :tracker, touch: true
  validates :name, presence: true
end

app/models/tracker.rb
class Tracker < ActiveRecord::Base
  before_create :generate_uniq_id
  has_many :subjects, dependent: :destroy

  validates :name, presence: true

  def to_param
    uniq_id
  end

  private

  def generate_uniq_id
    self.uniq_id = SecureRandom.hex(5)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_filter :find_tracker

  def create
    @tracker.subjects.create(subject_params)
    redirect_to @tracker
  end

  def vote
    s = @tracker.subjects.find(params[:id])
    s.increment!(:votes)
    redirect_to @tracker
  end

  private

  def find_tracker
    @tracker = Tracker.find_by_uniq_id(params[:tracker_id])
  end

  def subject_params
    params.require(:subject).permit(:name)
  end
end

app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  def new
    @tracker = Tracker.new
  end

  def create
    @t = Tracker.create!(tracker_params)
    redirect_to @t
  end

  def show
    @tracker = Tracker.find_by_uniq_id(params[:id])
    @subjects = @tracker.subjects.order("votes DESC")
    @subject = Subject.new
  end

  private

  def tracker_params
    params.require(:tracker).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def timeago(time, options = {})
    options[:class] ||= "timeago"
    content_tag(:time, time.to_s, options.merge(datetime: time.getutc.iso8601)) if time
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sales Safari Tracker</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">

  <%= yield %>

  <%= javascript_tag do %>
    SalesSafari.TimeAgo.replaceTimes()
  <% end %>
</body>
</html>

app/views/subjects/_form.html.erb
<%= form_for [tracker, subject] do |f| %>
  <%= f.text_field :name %>
  <button class="btn btn-info btn-lg">
    <i class="fa fa-plus"></i>
    <%= t("new_subject_button") %>
  </button>
<% end %>

app/views/subjects/_subject.html.erb
<% subjects.each do |subject| %>
  <tr>
    <td><%= button_to t("subject_vote_button"), vote_tracker_subject_path(tracker, subject), class: "btn btn-default" %></td>
    <td><%= subject.name %></td>
    <td><%= subject.votes %></td>
    <td><%= timeago(subject.updated_at) %></td>
  </tr>
<% end %>

app/views/trackers/new.html.erb
<section>
  <button class="btn btn-default btn-lg" data-behavior="new-tracker">
    <%= t("new_tracker_button") %>
    <i class="fa fa-arrow-right"></i>
  </button>

  <%= form_for @tracker do |f| %>
    <%= f.text_field :name, placeholder: "name" %>

    <button class="btn btn-success btn-lg">
      <i class="fa fa-plus"></i>
      <%= t("new_tracker_form_button") %>
    </button>
  <% end %>
</section>

app/views/trackers/show.html.erb
<h1><%= @tracker.name %></h1>
<section class="new-subject">
  <%= render partial: "subjects/form", locals: { subject: @subject, tracker: @tracker } %>
</section>

<section>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th></th>
        <th>Subject</th>
        <th>Votes</th>
        <th>Last updated</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "subjects/subject", locals: { subjects: @subjects, tracker: @tracker } %>
    </tbody>
  </table>
</section>